[versions]
junit = "6.0.3"


[libraries]
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
jackson = { module = "tools.jackson.module:jackson-module-kotlin", version = "3.1.3" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.23.0" }
assertj = { module = "org.assertj:assertj-core", version = "3.27.7" }
